package starmaker;

import java.util.Arrays;

import asmodeuscore.core.handler.ColorBlockHandler;
import micdoodle8.mods.galacticraft.core.Constants;
import net.minecraft.init.Blocks;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import starmaker.events.SMEventHandler;
import starmaker.proxy.CommonProxy;
import starmaker.utils.Log;
import starmaker.utils.MakerUtils;
import starmaker.utils.json.ParseFiles;
import starmaker.utils.zip.ZipUtils;

@Mod(
		   modid = StarMaker.MODID,
		   version = StarMaker.VERSION,
		   dependencies = Constants.DEPENDENCIES_FORGE + "required-after:galacticraftcore@[4.0.2.282,); required-after:galacticraftplanets; required-after:asmodeuscore@[1.0.4,)",
		   acceptedMinecraftVersions = "[1.12.2]",
		   name = StarMaker.NAME
		)
public class StarMaker {
	
	public static final int major_version = 1;
	public static final int minor_version = 0;
	public static final int build_version = 4;
	
	public static final String NAME = "StarMaker";
	public static final String MODID = "starmaker";
    public static final String VERSION = major_version + "." + minor_version + "." + build_version;
    public static final String ASSET_PREFIX = MODID;
    public static final String TEXTURE_PREFIX = ASSET_PREFIX + ":";
        
    public static String planetDir, moonDir, asteroidDir, satelliteDir;    
    public static String assetDir, biomesDir;

    @Instance(StarMaker.MODID)
    public static StarMaker instance;
    
    public static final Log LOG = new Log();
    
    @SidedProxy(clientSide=MODID+".proxy.ClientProxy", serverSide=MODID+".proxy.CommonProxy")
    public static CommonProxy proxy;   
    
    @EventHandler
    public void construct(FMLConstructionEvent e)
    {
    	ZipUtils.initZipFiles();
    }
    
    @EventHandler
    public void preInit(FMLPreInitializationEvent event) 
    {   
    	assetDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/bodies";
    	biomesDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/biomes";    	
    	planetDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/bodies/planets";    	
    	moonDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/bodies/moons";    	
    	asteroidDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/bodies/asteroids";    	
    	satelliteDir = event.getModConfigurationDirectory() + "/StarMaker/resources/" + CoreConfig.resourceDomain + "/bodies/satellites";    	
    	  	
    
    	initModInfo(event.getModMetadata());

    	proxy.preload();
		
		proxy.register_event(new SMEventHandler());
		    		
		ZipUtils.parseCelestialFiles();
		
		ColorBlockHandler.addLeavesBlock(Blocks.LEAVES.getDefaultState());
	    ColorBlockHandler.addLeavesBlock(Blocks.LEAVES2.getDefaultState());
	    ColorBlockHandler.addLeavesBlock(Blocks.VINE.getDefaultState());
	    ColorBlockHandler.addWaterBlock(Blocks.WATER.getDefaultState());
		ColorBlockHandler.addWaterBlock(Blocks.FLOWING_WATER.getDefaultState());
		ColorBlockHandler.addBlock(Blocks.GRASS.getDefaultState());
		ColorBlockHandler.addBlock(Blocks.TALLGRASS.getDefaultState());
		ColorBlockHandler.addBlock(Blocks.FLOWER_POT.getDefaultState());
    }
    
    @EventHandler
    public void init(FMLInitializationEvent event)
    {  
    	proxy.load();  	
    	ParseFiles.instance.printResults();
    }
    
    @EventHandler
    public void postInit(FMLPostInitializationEvent event) 
    {
    	proxy.postload();
    }
    
    private void initModInfo(ModMetadata info)
    {
        info.autogenerated = false;
        info.modId = MODID;
        info.name = NAME;
        info.version = VERSION;
        info.description = "StarMaker for Galacticraft 4!";
        info.authorList = Arrays.asList(
				"Vi[Told]#vitold",
				"AstroMaster#astromaster",
				"ZlayaSeledka#zlayaseledka",
				"AndRey#andrey5941"
		);
    }
       
    public static void info(Object message)
   	{ 
   		LOG.info(message.toString());
   	}  
    
    public static void debug(Object message)
   	{ 
   		if(MakerUtils.debug) 
   			LOG.info("[DEBUG StarMaker] ",  message.toString());
   	}  
    
}
